MESSAGES:
  CHAT_PREFIX: "&8[&6PlayerSentry&8] &7"
  PERMANENT_BAN_MESSAGE: "&cYou have been permanently banned from this server."
  TEMPORARY_BAN_MESSAGE: "&cYou have been banned from this server for xd."