name: PlayerSentry
version: '${project.version}'
main: com.eliaseeg.playersentry.PlayerSentry
api-version: '1.21'

commands:
  sban:
    description: Ban a player
    usage: /<command> <player>
  sunban:
    description: Unban a player
    usage: /<command> <player>
  stempban:
    description: Temporarily ban a player
    usage: /<command> <player> <time> <reason>
  stempunban:
    description: Temporarily unban a player
    usage: /<command> <player> <time> <reason>
  sblacklist:
    description: Blacklist a player
    usage: /<command> <player> <reason>
  sunblacklist:
    description: Unblacklist a player
    usage: /<command> <player>
  smute:
    description: Mute a player
    usage: /<command> <player> <reason>
  sunmute:
    description: Unmute a player
    usage: /<command> <player>
  stempmute:
    description: Temporarily mute a player
    usage: /<command> <player> <time> <reason>
  stempunmute:
    description: Temporarily unmute a player
    usage: /<command> <player> <time> <reason>
  skick:
    description: Kick a player
    usage: /<command> <player> <reason>